Adiciona estimadores de volatilidade (garman klass e parkinson)
GrupoTuring/turingquant pull request #24
Opened 2020-10-10 03:47 UTC by lucas-leme

- Adiciona as duas funções de estimadores de vol (garman e parkinson)
- Remove função duplicada de rolling_sharpe_ratio
- Adiciona parâmetro padrão de window em todas as funções (10 períodos)

![image](https://user-images.githubusercontent.com/49704353/95645028-6d95c680-0a91-11eb-90d1-328ddf800186.png)

2020-10-10 03:48 UTC, lucas-leme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Visualização rolling volatility](https://trello.com/c/3XUmJRMz/51-visualiza%C3%A7%C3%A3o-rolling-volatility)

2020-10-11 03:30 UTC, anor4k reviewed
Acho que seria melhor tirar a window padrão tbh

2020-10-11 03:30 UTC, anor4k commented on turingquant/metrics.py
>      """
não sei se é bom ter window padrão, principalmente com valores diferentes entre as funções

2020-10-11 03:30 UTC, anor4k commented on turingquant/metrics.py
> +def garman_klass_volatility(high_prices, low_prices, close_prices, open_prices, window=10, time_scale=1, plot=True):
não sei se gosto desse formato de parâmetros, mas acho que é o melhor q tem
talvez depois dê pra fazer um wrapper e passar um ativo com todos os dados

2020-10-12 18:01 UTC, lucas-leme commented on turingquant/metrics.py
>      """
Acho que vou deixar 1 como padrão, assim a gente não vai ter problema com o tamanho da série temporal

2020-10-12 18:03 UTC, lucas-leme commented on turingquant/metrics.py
> +def garman_klass_volatility(high_prices, low_prices, close_prices, open_prices, window=10, time_scale=1, plot=True):
Concordo q é zuado, podemos pensar em outra solução depois

2020-10-20 01:01 UTC, lucas-leme commented
up

2020-10-20 02:17 UTC, anor4k requested changes

2020-10-20 03:35 UTC, anor4k approved these changes

2020-10-20 03:41 UTC, merged