adiciona visualização de rolling std e ewma
GrupoTuring/turingquant pull request #26
Opened 2020-10-13 22:49 UTC by thalissa-reis

2020-10-14 11:15 UTC, aateg commented
@thalissa-reis acho que o nome deveria indicar melhor que é uma função pra plotar gráficos

2020-10-14 11:18 UTC, aateg approved these changes

2020-10-14 21:09 UTC, anor4k commented
é bom ter a docstring antes de dar o merge

2020-10-14 21:10 UTC, anor4k requested changes
docstring pls

2020-10-14 23:06 UTC, lucas-leme commented on turingquant/metrics.py
> +        returns = close_prices.pct_change()
```suggestion
    if ret == 'log':
        returns = np.log(close_prices/close_prices.shift(1))
    if ret == 'simp':
        returns = close_prices.pct_change()
    else:
        raise ValueError("Tipo de retorno inválido")
  
```

2020-10-14 23:13 UTC, lucas-leme reviewed
Não esquece de mudar de matplotlib para o plotly.

Acho que para a próxima sprint poderíamos implementar funções que calculam os retornos percentual e log. Daí se futuramente precisar não replica código

2020-10-14 23:13 UTC, lucas-leme commented on turingquant/metrics.py
> +        returns = close_prices.pct_change()
acho que seria legal se tive tratamento de erro, se o usuário inserir um tipo de retorno inválido.

2020-10-14 23:13 UTC, lucas-leme commented on turingquant/metrics.py
> +def ewma_volatility(close_prices,ret,window,plot=True):
Que tal colocar um nome de uma variável mais descritiva para o ret? 
```return_type``` ou algo do tipo

2020-10-14 23:13 UTC, lucas-leme commented on turingquant/metrics.py
> +        return rolling_std
Os mesmos cometários da função anterior para essa aqui...

2020-10-14 23:14 UTC, lucas-leme commented on turingquant/metrics.py
> +        returns = close_prices.pct_change()
@anor4k erros seriam em pt br ou em inglês?

2020-10-14 23:20 UTC, anor4k commented on turingquant/metrics.py
> +        returns = close_prices.pct_change()
acho que ptbr + mensagem original

2020-10-19 23:58 UTC, lucas-leme approved these changes
Aeee já tá manjando de git!!!

2020-10-20 00:11 UTC, anor4k approved these changes
acho que tá show

2020-10-20 00:53 UTC, merged