Remove janelas padrão
GrupoTuring/turingquant pull request #30
Opened 2020-10-20 03:47 UTC by lucas-leme

Esqueci de tirar de duas funções

2020-10-20 12:32 UTC, anor4k approved these changes

2020-10-20 12:33 UTC, anor4k requested changes
Consegue dar um bump na versão pra 0.1.6? no setup.py e docs/conf.py

2020-10-21 19:58 UTC, aateg commented
daora

2020-10-21 19:58 UTC, aateg approved these changes

2020-10-21 20:41 UTC, anor4k approved these changes

2020-10-21 20:41 UTC, merged