adiciona função para cálculo do retorno
GrupoTuring/turingquant pull request #32
Opened 2020-11-02 23:27 UTC by thalissa-reis

2020-11-02 23:33 UTC, lucas-leme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Função de retornos (numpy)](https://trello.com/c/6MgPPSTV/77-fun%C3%A7%C3%A3o-de-retornos-numpy)

2020-11-03 12:57 UTC, anor4k requested changes

2020-11-03 12:57 UTC, anor4k commented on turingquant/metrics.py
> +def retorno(close_prices,return_type='log',cumulative=False):
não tínhamos padronizado nomes de função em inglês?

2020-11-03 12:57 UTC, anor4k commented on turingquant/metrics.py
> +    Parâmetros:
Precisa ser `Args:` e `Returns:` na docstring

2020-11-03 15:20 UTC, juliapocciotti commented on turingquant/metrics.py
> +    Parâmetros:
@anor4k parece que também tem outras funções na biblioteca que estão com "Parâmetros" e "Retorna" na docstring

2020-11-03 15:45 UTC, lucas-leme commented on turingquant/metrics.py
> +        return returns
Gostei da ideia de ter o cálculo de retornos cumulativos! Mas acredito ser melhor separar as funções: Uma pra retornos e outra para retornos cumulativos (a partir de uma array de retornos.)

2020-11-03 17:26 UTC, anor4k commented on turingquant/metrics.py
> +    Parâmetros:
sim, tem que corrigir

2020-11-03 19:02 UTC, thalissa-reis commented on turingquant/metrics.py
> +def retorno(close_prices,return_type='log',cumulative=False):
Justíssimo! Mas ai coloco como "returns", pq se for "return" conflita com a return clássica

2020-11-03 19:03 UTC, thalissa-reis commented on turingquant/metrics.py
> +    Parâmetros:
mantém o resto do texto em português? ou deixa tudo em inglês?

2020-11-03 22:05 UTC, anor4k commented on turingquant/metrics.py
> +    Parâmetros:
resto em português! só aquilo que tem que ser em inglês pro readthedocs conseguir formatar certinho a documentação

2020-11-11 23:07 UTC, anor4k approved these changes

2020-11-11 23:08 UTC, anor4k requested changes
falta mudar o nome da função só eu acho

2020-11-11 23:08 UTC, anor4k commented on turingquant/metrics.py
> +def retorno(close_prices,return_type='log',cumulative=False):
aliás, up nisso

2020-11-11 23:37 UTC, thalissa-reis commented
> falta mudar o nome da função só eu acho

nossa, monguei. vou corrigir agora já

2020-11-12 02:01 UTC, anor4k approved these changes
agora tá check 👍
tacale merge

2020-11-14 18:24 UTC, merged